language: go

go:
  - 1.4

before_install:
  - go get github.com/fritzing/fzp
  - cd $GOPATH/src/github.com/fritzing/fzp; go build

script:
  - $GOPATH/src/github.com/fritzing/fzp/fzp -v
  - $GOPATH/src/github.com/fritzing/fzp/fzp validate -d $GOPATH/src/github.com/fritzing/fritzing-parts/core
