language: go

go:
  - 1.6

install:
  - echo "install fzp tool"
  - go get github.com/fritzing/fzp/bin/fzp
  - echo "fzp succefully installed. Version:"
  - fzp -v

script:
  - echo "run fzp validation tool in fritzing-parts/core"
  - fzp validate -d $HOME/gopath/src/github.com/fritzing/fritzing-parts/core
