title: fritzing-parts
description: the fritzing parts api
url: "https://paulvollmer.github.io/fritzing-parts" # "http://localhost:4000"
webrick:
  headers:
    Content-Type: application/json; charset=utf-8
